import { sendJson, handleCors } from './lib/utils.js';

const API_DOCS = {
  version: '1.0.0',
  baseUrl: '/api',
  authentication: {
    type: 'JWT Bearer Token',
    header: 'Authorization: Bearer <token>',
    note: 'Obtain token from /api/auth/login or /api/auth/register',
  },
  endpoints: [
    { method: 'POST', path: '/auth/register', description: 'Create new account', body: { email: 'string', password: 'string', name: 'string', company: 'string?' } },
    { method: 'POST', path: '/auth/login', description: 'Authenticate and get tokens', body: { email: 'string', password: 'string' } },
    { method: 'POST', path: '/auth/forgot-password', description: 'Request password reset', body: { email: 'string' } },
    { method: 'POST', path: '/auth/reset-password', description: 'Reset password with token', body: { token: 'string', password: 'string' } },
    { method: 'POST', path: '/auth/verify-email', description: 'Verify email address', body: { token: 'string' } },
    { method: 'POST', path: '/auth/resend-verification', description: 'Resend verification email', body: { email: 'string' } },
    { method: 'POST', path: '/auth/2fa-setup', description: 'Enable TOTP 2FA', auth: true },
    { method: 'POST', path: '/auth/2fa-verify', description: 'Verify TOTP code', auth: true, body: { code: 'string', action: 'setup|login' } },
    { method: 'GET', path: '/me', description: 'Get current user profile', auth: true },
    { method: 'PATCH', path: '/me', description: 'Update profile', auth: true, body: { name: 'string?', company: 'string?' } },
    { method: 'GET', path: '/clients', description: 'List clients', auth: true },
    { method: 'POST', path: '/clients', description: 'Create client', auth: true, body: { name: 'string', email: 'string', contact: 'string?', type: 'string?', status: 'string?' } },
    { method: 'GET', path: '/clients/:id', description: 'Get client by ID', auth: true },
    { method: 'PATCH', path: '/clients/:id', description: 'Update client', auth: true },
    { method: 'DELETE', path: '/clients/:id', description: 'Delete client', auth: true },
    { method: 'GET', path: '/clients/:id/activity', description: 'Get client activity timeline', auth: true },
    { method: 'GET', path: '/projects', description: 'List projects', auth: true },
    { method: 'POST', path: '/projects', description: 'Create project', auth: true },
    { method: 'GET', path: '/invoices', description: 'List invoices', auth: true },
    { method: 'POST', path: '/invoices', description: 'Create invoice', auth: true },
    { method: 'GET', path: '/invoices/:id/pdf', description: 'Generate invoice PDF', auth: true },
    { method: 'GET', path: '/payments', description: 'List payments', auth: true },
    { method: 'POST', path: '/payments', description: 'Record payment', auth: true },
    { method: 'POST', path: '/payments/stripe', description: 'Create Stripe payment intent', auth: true, body: { invoiceId: 'number', amount: 'number', currency: 'string?' } },
    { method: 'GET', path: '/recurring-invoices', description: 'List recurring invoice templates', auth: true },
    { method: 'POST', path: '/recurring-invoices', description: 'Create recurring invoice template', auth: true },
    { method: 'GET', path: '/subscriptions', description: 'List subscriptions', auth: true },
    { method: 'POST', path: '/subscriptions', description: 'Create subscription', auth: true },
    { method: 'GET', path: '/proposals', description: 'List proposals', auth: true },
    { method: 'POST', path: '/proposals', description: 'Create proposal', auth: true },
    { method: 'PATCH', path: '/proposals/:id', description: 'Update/accept proposal', auth: true },
    { method: 'GET', path: '/tasks', description: 'List tasks', auth: true },
    { method: 'POST', path: '/tasks', description: 'Create task', auth: true },
    { method: 'PATCH', path: '/tasks/:id', description: 'Update task status/assignee', auth: true },
    { method: 'GET', path: '/files', description: 'List files', auth: true },
    { method: 'POST', path: '/files', description: 'Create file record', auth: true },
    { method: 'POST', path: '/upload', description: 'Upload file to S3', auth: true, body: { fileName: 'string', fileType: 'string', base64Data: 'string' } },
    { method: 'GET', path: '/comments', description: 'List comments', auth: true },
    { method: 'POST', path: '/comments', description: 'Post comment (supports @mentions)', auth: true, body: { workAreaId: 'number', text: 'string', parentId: 'number?' } },
    { method: 'GET', path: '/approvals', description: 'List approvals', auth: true },
    { method: 'POST', path: '/approvals', description: 'Create approval request', auth: true },
    { method: 'GET', path: '/team', description: 'List team members', auth: true },
    { method: 'POST', path: '/team', description: 'Invite team member', auth: true },
    { method: 'GET', path: '/timesheets', description: 'List time entries', auth: true },
    { method: 'POST', path: '/timesheets', description: 'Log time entry', auth: true },
    { method: 'GET', path: '/capacity', description: 'Team capacity view', auth: true },
    { method: 'GET', path: '/search', description: 'Global search', auth: true, query: { q: 'string' } },
    { method: 'GET', path: '/export', description: 'Export data (CSV/JSON)', auth: true, query: { type: 'clients|invoices|projects', format: 'csv|json' } },
    { method: 'GET', path: '/audit-log', description: 'View audit logs', auth: true },
    { method: 'GET', path: '/notifications', description: 'Get notifications', auth: true },
    { method: 'GET', path: '/webhooks', description: 'List webhooks', auth: true },
    { method: 'POST', path: '/webhooks', description: 'Create webhook', auth: true },
    { method: 'GET', path: '/reminders', description: 'List reminders', auth: true },
    { method: 'POST', path: '/reminders', description: 'Create reminder', auth: true },
    { method: 'GET', path: '/workflows', description: 'List automation workflows', auth: true },
    { method: 'POST', path: '/workflows', description: 'Create workflow rule', auth: true },
    { method: 'POST', path: '/ai-assistant', description: 'AI helper (summarize, suggest, follow-up)', auth: true, body: { action: 'string', text: 'string?', context: 'object?' } },
    { method: 'POST', path: '/contact', description: 'Public contact form', auth: false },
    { method: 'POST', path: '/early-access', description: 'Public early access signup', auth: false },
    { method: 'POST', path: '/setup', description: 'Run database migrations', auth: false },
  ],
  webhooks: {
    events: ['invoice.created', 'invoice.paid', 'task.completed', 'approval.requested', 'approval.approved', 'client.created', 'payment.received'],
    signature: 'X-Webhook-Signature header with HMAC-SHA256',
  },
};

export default async function handler(req, res) {
  if (handleCors(req, res)) return;
  sendJson(res, 200, API_DOCS);
}
